name = "shorts"
type = "webpack"
account_id = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = false
route = 'a.sascha.link/*'
compatibility_date = "2021-10-11"

[site]
bucket = "build"
entry-point = "workers-site"
