name = "shorts-dev"
type = "javascript"
account_id = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-11-23"

[env.production]
name = "shorts"
workers_dev = false
route = "a.sascha.link/*"

[build]
command = ""

[build.upload]
format = "service-worker"

[site]
bucket = "build"
entry-point = "workers-site"
