name = "shorts"
type = "javascript"
account_id = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-11"

[build]
command = ""

[build.upload]
format = "service-worker"

[site]
bucket = "build"
entry-point = "workers-site"
