name = "shorts"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-11"

[site]
bucket = "build"
entry-point = "workers-site"
